#!/usr/bin/env node
// check_deployable.mjs — v1.0
//
// WHY THIS EXISTS (v7.85 post-mortem). Every harness in this project runs
// against the working tree, so a change can pass every gate and still have
// no route to production. That happened: v7.85 edited eight app files plus
// scripts/sync_af411.py and .github/workflows/sync-af411.yml, but the
// release zip contained only the eight app files. The app half shipped and
// the sync half silently stayed behind — the owner noticed days later when
// the Discord embed still had no AF411 ids, and af411-paths.json had never
// been generated either. deploy.html ALREADY routed .py and .yml correctly;
// the files just were not put in the zip. Nothing in CI could see that,
// because "did this reach the repo" is not a property of the source tree.
//
// Two modes:
//
//   node scripts/check_deployable.mjs
//       Audit mode (CI). Every tracked file must have a PATH_MAP entry in
//       deploy.html pointing at exactly its path, or match EXEMPT below.
//       Catches a NEW file added with no way to deploy it.
//
//   node scripts/check_deployable.mjs --zip <release.zip> --since <git-ref>
//       Release mode. Every file changed since <git-ref> that is deployable
//       must actually be IN the zip. This is the check that would have
//       caught v7.85.
//
// Also flags basename collisions. deploy.html zips are FLAT and keyed by
// basename, so two repo paths ending in the same filename cannot both be
// deployed — that is why backend/README.md is mapped as 'backend-README.md'.
//
// Exit 0 = clean, 1 = problems found.

import { readFileSync } from 'fs';
import { execFileSync } from 'child_process';
import path from 'path';

const args = process.argv.slice(2);
const argOf = (name) => {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
};
const repo = argOf('--repo') || process.cwd();
const zipPath = argOf('--zip');
const since = argOf('--since');

// Files that legitimately have no deploy.html route: written by a bot or a
// tool that commits directly, or not shipped at all. Anything NOT matched
// here needs a PATH_MAP entry.
const EXEMPT = [
  /^images\//,                    // sync_af411.py commits these directly
  /\.(jpg|jpeg|png|gif|webp|mp3|ico)$/i,
  /^af411-paths\.json$/,          // generated by sync_af411.py (v7.85)
  /^loadouts-suggested\.json$/,   // generated
  /__pycache__/,
  /^\.gitignore$/,
  /^\.github\/(?!workflows\/)/,   // issue templates etc, not deployed
];
// Data files that DO have a PATH_MAP entry but are normally committed by a
// bot or the editor — they must not be demanded in a release zip.
const NOT_IN_RELEASE = [
  /^figures\.json$/, /^figures-pending\.json$/, /^figures-rejected\.json$/,
  /^loadouts\.json$/, /^af411-paths\.json$/, /^images\//,
];

let problems = 0;
const bad = (msg, detail = '') => {
  problems++;
  console.log('  ✗ ' + msg + (detail ? '\n      ' + detail : ''));
};

// ── Parse PATH_MAP out of deploy.html ─────────────────────────────
// v1.2: routing table source. deploy.html is the normal source and is what
// this repo uses today. The deploy-path-map.json branch is a fallback for
// the case where deploy.html is NOT in the repo — moving the admin tools to
// a separate origin (SEC-01) was evaluated and rejected as too much effort,
// but if it is ever revisited this gate keeps working without changes: the
// tools read no location.origin and REPO is a hardcoded constant, so only
// this routing table would need relocating. No such JSON exists right now.
let PATH_MAP = {};
let mapSource = '';
try {
  const j = JSON.parse(readFileSync(path.join(repo, 'deploy-path-map.json'), 'utf8'));
  if (j && j.paths && typeof j.paths === 'object') { PATH_MAP = j.paths; mapSource = 'deploy-path-map.json'; }
} catch { /* fall through to deploy.html */ }
if (!mapSource) {
  try {
    const src = readFileSync(path.join(repo, 'deploy.html'), 'utf8');
    const blk = src.match(/const PATH_MAP = \{([\s\S]*?)\n\};/);
    if (blk) {
      for (const m of blk[1].matchAll(/'([^']+)'\s*:\s*'([^']+)'/g)) PATH_MAP[m[1]] = m[2];
      mapSource = 'deploy.html';
    }
  } catch { /* handled below */ }
}
if (!mapSource) {
  console.log('✗ No routing table: deploy.html is not present and no');
  console.log('  deploy-path-map.json fallback exists either.');
  process.exit(1);
}
const targetToKey = new Map(Object.entries(PATH_MAP).map(([k, v]) => [v, k]));

// v1.4: deploy.html's resolveRepoPath() falls back to extension rules when a
// name has no explicit PATH_MAP entry, so a new .py or .yml genuinely IS
// deployable without one. Mirroring those rules here stops this gate failing
// on files the tool would place correctly — which it did the moment
// scripts/optimize_images.py and .github/workflows/optimize-images.yml were
// added. Keep in sync with resolveRepoPath in deploy.html.
function fallbackPath(name) {
  if (/\.js$/i.test(name))                 return 'js/' + name;
  if (/\.(jpe?g|png|gif|webp)$/i.test(name)) return 'images/' + name;
  if (/\.py$/i.test(name))                 return 'scripts/' + name;
  if (/\.ya?ml$/i.test(name))              return '.github/workflows/' + name;
  if (/\.json$/i.test(name))               return name;
  if (/\.html$/i.test(name))               return name;
  return null;
}
// A repo path is routable if an explicit entry points at it, OR the extension
// fallback for its basename resolves to exactly that path.
const routable = (f) => targetToKey.has(f) || fallbackPath(path.basename(f)) === f;
// The key deploy.html would use for a repo path (explicit entry, else basename).
const keyFor = (f) => targetToKey.get(f) || (fallbackPath(path.basename(f)) === f ? path.basename(f) : null);

const git = (...a) => execFileSync('git', a, { cwd: repo, encoding: 'utf8' }).trim();
const tracked = git('ls-files').split('\n').filter(Boolean);
const exempt = f => EXEMPT.some(rx => rx.test(f));

console.log(`PATH_MAP: ${Object.keys(PATH_MAP).length} entries (from ${mapSource}) · tracked files: ${tracked.length}\n`);

// ── 1. Audit: every tracked file needs a route ────────────────────
console.log('Audit — tracked files with no deploy route:');
let unrouted = 0;
for (const f of tracked) {
  if (exempt(f)) continue;
  if (!routable(f)) { bad(`no deploy route (no PATH_MAP entry and no extension fallback): ${f}`); unrouted++; }
}
if (!unrouted) console.log('  ✓ every tracked file is routable');

// ── 2. PATH_MAP entries pointing at files that no longer exist ────
console.log('\nAudit — PATH_MAP entries with no such file:');
const trackedSet = new Set(tracked);
let stale = 0;
for (const [key, target] of Object.entries(PATH_MAP)) {
  if (!trackedSet.has(target)) { bad(`PATH_MAP '${key}' → '${target}' (not tracked)`); stale++; }
}
if (!stale) console.log('  ✓ every PATH_MAP target exists');

// ── 3. Basename collisions (zips are flat) ────────────────────────
console.log('\nAudit — basename collisions (flat zip hazard):');
const byBase = new Map();
for (const f of tracked) {
  if (exempt(f)) continue;
  const b = path.basename(f);
  if (!byBase.has(b)) byBase.set(b, []);
  byBase.get(b).push(f);
}
let collisions = 0;
for (const [b, files] of byBase) {
  if (files.length < 2) continue;
  // Fine as long as at most one of them is keyed by the bare basename.
  const bareKeyed = files.filter(f => PATH_MAP[b] === f);
  if (bareKeyed.length > 1 || (bareKeyed.length === 1 && files.some(f => !targetToKey.has(f)))) {
    bad(`basename '${b}' maps ambiguously`, files.join('  vs  '));
    collisions++;
  }
}
if (!collisions) console.log('  ✓ no ambiguous basenames');

// ── 4. Release mode ───────────────────────────────────────────────
if (zipPath || since) {
  console.log('\nRelease check:');
  if (!zipPath || !since) {
    bad('release mode needs BOTH --zip and --since');
  } else {
    // Minimal zip central-directory reader — no dependencies.
    const names = [];
    try {
      const buf = readFileSync(zipPath);
      let eocd = -1;
      for (let i = buf.length - 22; i >= 0; i--) {
        if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
      }
      if (eocd < 0) throw new Error('no end-of-central-directory record');
      const count = buf.readUInt16LE(eocd + 10);
      let off = buf.readUInt32LE(eocd + 16);
      for (let i = 0; i < count; i++) {
        if (buf.readUInt32LE(off) !== 0x02014b50) throw new Error('bad central directory entry');
        const nLen = buf.readUInt16LE(off + 28);
        const eLen = buf.readUInt16LE(off + 30);
        const cLen = buf.readUInt16LE(off + 32);
        names.push(buf.toString('utf8', off + 46, off + 46 + nLen));
        off += 46 + nLen + eLen + cLen;
      }
    } catch (e) {
      bad(`could not read zip ${zipPath}: ${e.message}`);
    }

    const inZip = new Set(names.map(n => path.basename(n)));
    let changed = [];
    try {
      changed = git('diff', '--name-only', `${since}..HEAD`).split('\n').filter(Boolean);
    } catch (e) {
      bad(`could not diff against '${since}': ${e.message.split('\n')[0]}`);
    }

    const needed = changed.filter(f =>
      !exempt(f) && !NOT_IN_RELEASE.some(rx => rx.test(f)) && routable(f));
    console.log(`  changed since ${since}: ${changed.length} · deployable: ${needed.length} · in zip: ${inZip.size}`);

    let missing = 0;
    for (const f of needed) {
      const key = keyFor(f);
      if (!inZip.has(key)) {
        bad(`CHANGED BUT NOT IN ZIP: ${f}`, `deploy.html expects it as '${key}'`);
        missing++;
      }
    }
    if (!missing && needed.length) console.log('  ✓ every changed deployable file is in the zip');

    // v1.1 ORDERING TRAP. deploy.html routes a zip entry through the PATH_MAP
    // of the deploy.html ALREADY RUNNING IN THE BROWSER. So a release that
    // adds a NEW file *and* the PATH_MAP entry that routes it, in one zip,
    // silently drops the new file: the old deploy.html has never heard of it.
    // That is exactly how v7.87 shipped lint.yml's "Version stamps" step
    // while scripts/check_version_stamps.mjs never landed — leaving CI red
    // with a module-not-found. Deploy deploy.html FIRST, then the new file.
    // v1.3: compare against the routing table AS IT WAS at `since` — whatever
    // carried it then (deploy-path-map.json, or deploy.html before it was
    // taken off the origin). The earlier version only ran when deploy.html
    // was in the zip, which missed the commoner case: a new file whose route
    // exists only in the maintainer's LOCAL deploy.html. Either way the
    // running tool cannot place an entry it has never heard of.
    let prevKeys = null;
    for (const [ref, parse] of [
      [`${since}:deploy-path-map.json`, t => Object.keys((JSON.parse(t).paths) || {})],
      [`${since}:deploy.html`, t => {
        const b = t.match(/const PATH_MAP = \{([\s\S]*?)\n\};/);
        return b ? [...b[1].matchAll(/'([^']+)'\s*:/g)].map(m => m[1]) : null;
      }],
    ]) {
      try {
        const txt = execFileSync('git', ['show', ref], { cwd: repo, encoding: 'utf8', stdio: ['ignore','pipe','ignore'] });
        const keys = parse(txt);
        if (keys && keys.length) { prevKeys = new Set(keys); break; }
      } catch { /* try the next source */ }
    }
    if (prevKeys) {
      for (const n of inZip) {
        // Only an EXPLICIT entry can be "new"; a file relying on the
        // extension fallback needs no entry, so it can never hit this trap.
        if (n === 'deploy.html' || !PATH_MAP[n]) continue;
        if (!prevKeys.has(n)) {
          bad(`ORDERING: '${n}' (${PATH_MAP[n]}) is routed by a PATH_MAP entry that did not exist at ${since}`,
              'the deploy.html doing the upload must already know this route, or the file is silently dropped');
        }
      }
    }

    for (const n of inZip) {
      if (!PATH_MAP[n] && !fallbackPath(n)) bad(`zip entry '${n}' has no PATH_MAP entry and no extension fallback — deploy.html will not know where to put it`);
      else if (!changed.includes(PATH_MAP[n] || fallbackPath(n)))
        console.log(`  ⚠ zip contains '${n}' but it did not change since ${since} (harmless, just noise)`);
    }
  }
}

console.log(problems ? `\n✗ ${problems} problem(s) found` : '\n✓ all deployability checks pass');
process.exit(problems ? 1 : 0);
