#!/usr/bin/env node
// check_deployable.mjs — v1.0
//
// WHY THIS EXISTS (v7.85 post-mortem). Every harness in this project runs
// against the working tree, so a change can pass every gate and still have
// no route to production. That happened: v7.85 edited eight app files plus
// scripts/sync_af411.py and .github/workflows/sync-af411.yml, but the
// release zip contained only the eight app files. The app half shipped and
// the sync half silently stayed behind — the owner noticed days later when
// the Discord embed still had no AF411 ids, and af411-paths.json had never
// been generated either. deploy.html ALREADY routed .py and .yml correctly;
// the files just were not put in the zip. Nothing in CI could see that,
// because "did this reach the repo" is not a property of the source tree.
//
// Two modes:
//
//   node scripts/check_deployable.mjs
//       Audit mode (CI). Every tracked file must have a PATH_MAP entry in
//       deploy.html pointing at exactly its path, or match EXEMPT below.
//       Catches a NEW file added with no way to deploy it.
//
//   node scripts/check_deployable.mjs --zip <release.zip> --since <git-ref>
//       Release mode. Every file changed since <git-ref> that is deployable
//       must actually be IN the zip. This is the check that would have
//       caught v7.85.
//
// Also flags basename collisions. deploy.html zips are FLAT and keyed by
// basename, so two repo paths ending in the same filename cannot both be
// deployed — that is why backend/README.md is mapped as 'backend-README.md'.
//
// Exit 0 = clean, 1 = problems found.

import { readFileSync } from 'fs';
import { execFileSync } from 'child_process';
import path from 'path';

const args = process.argv.slice(2);
const argOf = (name) => {
  const i = args.indexOf(name);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
};
const repo = argOf('--repo') || process.cwd();
const zipPath = argOf('--zip');
const since = argOf('--since');

// Files that legitimately have no deploy.html route: written by a bot or a
// tool that commits directly, or not shipped at all. Anything NOT matched
// here needs a PATH_MAP entry.
const EXEMPT = [
  /^images\//,                    // sync_af411.py commits these directly
  /\.(jpg|jpeg|png|gif|webp|mp3|ico)$/i,
  /^af411-paths\.json$/,          // generated by sync_af411.py (v7.85)
  /^loadouts-suggested\.json$/,   // generated
  /__pycache__/,
  /^\.gitignore$/,
  /^\.github\/(?!workflows\/)/,   // issue templates etc, not deployed
];
// Data files that DO have a PATH_MAP entry but are normally committed by a
// bot or the editor — they must not be demanded in a release zip.
const NOT_IN_RELEASE = [
  /^figures\.json$/, /^figures-pending\.json$/, /^figures-rejected\.json$/,
  /^loadouts\.json$/, /^af411-paths\.json$/, /^images\//,
];

let problems = 0;
const bad = (msg, detail = '') => {
  problems++;
  console.log('  ✗ ' + msg + (detail ? '\n      ' + detail : ''));
};

// ── Parse PATH_MAP out of deploy.html ─────────────────────────────
let PATH_MAP = {};
try {
  const src = readFileSync(path.join(repo, 'deploy.html'), 'utf8');
  const blk = src.match(/const PATH_MAP = \{([\s\S]*?)\n\};/);
  if (!blk) {
    console.log('✗ Could not locate PATH_MAP in deploy.html — has it been renamed?');
    process.exit(1);
  }
  for (const m of blk[1].matchAll(/'([^']+)'\s*:\s*'([^']+)'/g)) PATH_MAP[m[1]] = m[2];
} catch (e) {
  console.log('✗ Could not read deploy.html: ' + e.message);
  process.exit(1);
}
const targetToKey = new Map(Object.entries(PATH_MAP).map(([k, v]) => [v, k]));

const git = (...a) => execFileSync('git', a, { cwd: repo, encoding: 'utf8' }).trim();
const tracked = git('ls-files').split('\n').filter(Boolean);
const exempt = f => EXEMPT.some(rx => rx.test(f));

console.log(`PATH_MAP: ${Object.keys(PATH_MAP).length} entries · tracked files: ${tracked.length}\n`);

// ── 1. Audit: every tracked file needs a route ────────────────────
console.log('Audit — tracked files with no deploy route:');
let unrouted = 0;
for (const f of tracked) {
  if (exempt(f)) continue;
  if (!targetToKey.has(f)) { bad(`no PATH_MAP entry: ${f}`); unrouted++; }
}
if (!unrouted) console.log('  ✓ every tracked file is routable');

// ── 2. PATH_MAP entries pointing at files that no longer exist ────
console.log('\nAudit — PATH_MAP entries with no such file:');
const trackedSet = new Set(tracked);
let stale = 0;
for (const [key, target] of Object.entries(PATH_MAP)) {
  if (!trackedSet.has(target)) { bad(`PATH_MAP '${key}' → '${target}' (not tracked)`); stale++; }
}
if (!stale) console.log('  ✓ every PATH_MAP target exists');

// ── 3. Basename collisions (zips are flat) ────────────────────────
console.log('\nAudit — basename collisions (flat zip hazard):');
const byBase = new Map();
for (const f of tracked) {
  if (exempt(f)) continue;
  const b = path.basename(f);
  if (!byBase.has(b)) byBase.set(b, []);
  byBase.get(b).push(f);
}
let collisions = 0;
for (const [b, files] of byBase) {
  if (files.length < 2) continue;
  // Fine as long as at most one of them is keyed by the bare basename.
  const bareKeyed = files.filter(f => PATH_MAP[b] === f);
  if (bareKeyed.length > 1 || (bareKeyed.length === 1 && files.some(f => !targetToKey.has(f)))) {
    bad(`basename '${b}' maps ambiguously`, files.join('  vs  '));
    collisions++;
  }
}
if (!collisions) console.log('  ✓ no ambiguous basenames');

// ── 4. Release mode ───────────────────────────────────────────────
if (zipPath || since) {
  console.log('\nRelease check:');
  if (!zipPath || !since) {
    bad('release mode needs BOTH --zip and --since');
  } else {
    // Minimal zip central-directory reader — no dependencies.
    const names = [];
    try {
      const buf = readFileSync(zipPath);
      let eocd = -1;
      for (let i = buf.length - 22; i >= 0; i--) {
        if (buf.readUInt32LE(i) === 0x06054b50) { eocd = i; break; }
      }
      if (eocd < 0) throw new Error('no end-of-central-directory record');
      const count = buf.readUInt16LE(eocd + 10);
      let off = buf.readUInt32LE(eocd + 16);
      for (let i = 0; i < count; i++) {
        if (buf.readUInt32LE(off) !== 0x02014b50) throw new Error('bad central directory entry');
        const nLen = buf.readUInt16LE(off + 28);
        const eLen = buf.readUInt16LE(off + 30);
        const cLen = buf.readUInt16LE(off + 32);
        names.push(buf.toString('utf8', off + 46, off + 46 + nLen));
        off += 46 + nLen + eLen + cLen;
      }
    } catch (e) {
      bad(`could not read zip ${zipPath}: ${e.message}`);
    }

    const inZip = new Set(names.map(n => path.basename(n)));
    let changed = [];
    try {
      changed = git('diff', '--name-only', `${since}..HEAD`).split('\n').filter(Boolean);
    } catch (e) {
      bad(`could not diff against '${since}': ${e.message.split('\n')[0]}`);
    }

    const needed = changed.filter(f =>
      !exempt(f) && !NOT_IN_RELEASE.some(rx => rx.test(f)) && targetToKey.has(f));
    console.log(`  changed since ${since}: ${changed.length} · deployable: ${needed.length} · in zip: ${inZip.size}`);

    let missing = 0;
    for (const f of needed) {
      const key = targetToKey.get(f);
      if (!inZip.has(key)) {
        bad(`CHANGED BUT NOT IN ZIP: ${f}`, `deploy.html expects it as '${key}'`);
        missing++;
      }
    }
    if (!missing && needed.length) console.log('  ✓ every changed deployable file is in the zip');

    for (const n of inZip) {
      if (!PATH_MAP[n]) bad(`zip entry '${n}' has no PATH_MAP entry — deploy.html will not know where to put it`);
      else if (!changed.includes(PATH_MAP[n]))
        console.log(`  ⚠ zip contains '${n}' but it did not change since ${since} (harmless, just noise)`);
    }
  }
}

console.log(problems ? `\n✗ ${problems} problem(s) found` : '\n✓ all deployability checks pass');
process.exit(problems ? 1 : 0);
